### ISSUE TITLE
参加メッセージにLink推奨を追記

### ISSUE THREAD

**Issue by yuuahp** [jaoafa/Javajaotan2#14]
## 内容

参加メッセージに`/link`を推奨するメッセージも入れた方がいいと思います
![image](https://user-images.githubusercontent.com/53546237/120158129-bb348e80-c22e-11eb-9bb1-b71717460179.png)

**Comment by yuuahp** [comment]
私やってもいいですか

**Comment by book000** [comment]
`#greeting` でどうせ既に言ってるし、これ書いたところで大抵linkしないから要らないんじゃないか…？？
https://github.com/jaoafa/Javajaotan/blob/c26e048dd7c3a5a744a7320d306219dfbb20f5e4/src/main/java/com/jaoafa/Javajaotan/Channel/Channel_603841992404893707.java#L47

**Comment by yuuahp** [comment]
たしかに

**Comment by yuuahp** [comment]
.
