### ISSUE TITLE
Java 11への対応

### ISSUE THREAD

**Issue by book000** [jaoafa/Javajaotan2#19]
開発環境、SDKの変更。

LTS(Long Term Support)が11なので、そちらに切り替える。

**Comment by yuuahp** [comment]
ローカルテスト環境も11が必要ですか？
本日調子に乗って16にしてしまったのですが

**Comment by yuuahp** [comment]
よく考えたらそりゃそうか...

**Comment by book000** [comment]
必要。開発環境として。
IDEAのプロジェクト設定？だかにプロジェクトSDKの設定があるじゃん？そこから11のSDK落として指定するだけでいいと思う

**Comment by book000** [comment]
ただ、Mavenの設定をまだ11に対応させてないから多分ビルドできないのでそれはちょっと待って(今若干忙しい)

**Comment by yuuahp** [comment]
JAVA_HOMEは11の方が...?

**Comment by book000** [comment]
いや？IDEAの中の設定で切り替えるだけでいいんじゃない？
下の画像みたいに(別プロジェクトですまんけど)、プロジェクトSDKとプロジェクトの言語レベルだけ切り替えればいいと思う

![image](https://user-images.githubusercontent.com/8929706/121527517-73371800-ca35-11eb-89b1-65aee1ed2862.png)

**Comment by book000** [comment]
少なくとも、Javajaotan無印は今日バイト先で作業したときにこれで通った

**Comment by yuuahp** [comment]
ホンマか...
結構簡単なのね

**Comment by book000** [comment]
「たぶん」ね。ビルドだけしかテストしてないからどこでバグるかわかんない

(実はサーバ側のJava11対応のほうがめんどくさい…)

**Comment by yuuahp** [comment]
混在するならjEnvとか？

**Comment by book000** [comment]
`alternatives` というLinuxのコマンドがあって、それ使って切り替え〜ってことができるとか出来ないとか…

**Comment by yuuahp** [comment]
なんか使ったことある気がする...

**Comment by book000** [comment]
お、まじ？利用経験なくて動作が微妙に理解できてないんだよね…(まだ実機で試してないけど)

**Comment by yuuahp** [comment]
![image](https://user-images.githubusercontent.com/53546237/121529174-1a687f00-ca37-11eb-9a22-f0256dc6f15c.png)
aptから複数Javaインストールしたら選択できますよ的なことしかわからない...
全体に選択したJavaが適用される

**Comment by book000** [comment]
ディレクトリごとにこれが保持されるのかとか、どうなのかわからんのよね〜
その時のターミナルのときだけパスが保持されるのかなあ

**Comment by yuuahp** [comment]
選択した時点で全体に適用されたはず
再選択するまで永遠に保持される

**Comment by book000** [comment]
うへ〜。systemctlとかで半永久的に動作させる時にこの辺の制御どうすらのか微妙だな〜

**Comment by book000** [comment]
Javajaotan無印でJava11の開発環境変更と動作環境の切り替えに成功しました。(デプロイやGitHub Actionsその他もok)
Javajaotan2でも同様の作業が実施できると見込んでます。

MyMaid4についてはJava11に上げる理由が「サーババージョンを1.17に上げる」以外に無いので、とりあえず見送りです。Java8〜11までの間の機能で無茶苦茶使いやすそう・使いたいって機能があるなら上げることを検討するので言ってください。
