### ISSUE TITLE
greetingチャンネルの案内メッセージが余計に2回表示されている

### ISSUE THREAD

**Issue by minhero-exp** [jaoafa/Javajaotan2#256]
## 不具合の説明

greetingチャンネルで新規参加者が「jao」「afa」と発言した際に、「挨拶していただきありがとうございます！この後は～」のメッセージが2回表示されているように見えます。

## スクリーンショット

![image](https://user-images.githubusercontent.com/75877469/165883361-03ca54e1-e0ec-479e-826c-84386771ac80.png)

**Comment by book000** [comment]
過去のJavajaotan無印と、Javajaotan2の実装が両方動作したことによるものなようです。無印の機能を無効化しました。
