### ISSUE TITLE
NitrotanじゃないのにNitrotanが付与される

### ISSUE THREAD

**Issue by jaotan** [jaoafa/Javajaotan2#268]
## 不具合と思われるメッセージ (または報告)

2022-05-19 16:45:44.308 に送信された `jaotan#6066` による `#perm-sync` でのメッセージ

URL: https://discord.com/channels/597378876556967936/891021520099500082/976752504714985533

## 不具合報告者

`Omelet#4429`

**Comment by book000** [comment]
- Nitrotanではないのに自動でNitrotanが付与されてしまう
- isOtherGuildEmojiでの判定
- 鯖の絵文字キャッシュ更新がうまくいってない？
