### ISSUE TITLE
改行を含むコマンド実行不具合

### ISSUE THREAD

**Issue by jaotan** [jaoafa/Javajaotan2#315]
## 不具合と思われるメッセージ (または報告)

2022-08-15 17:13:38.121 に送信された `jaotan#6066` による `#vc` でのメッセージ

URL: https://discord.com/channels/597378876556967936/623153228267388958/1008649657368449034

## 不具合報告者

`zakuro#4096`

**Comment by book000** [comment]
再現せず。一旦クローズ
