### ISSUE TITLE
3か月通知が複数回行われる + 自動解除されない

### ISSUE THREAD

**Issue by jaotan** [jaoafa/Javajaotan2#316]
## 不具合と思われるメッセージ (または報告)

2022-08-16 00:00:35.683 に送信された `jaotan#6066` による `#general` でのメッセージ

URL: https://discord.com/channels/597378876556967936/597419057251090443/1008752072046419988

## 不具合報告者

`Omelet#4429`

**Comment by book000** [comment]
#318で解決したことを確認。
