### ISSUE TITLE
翻訳元の言語と翻訳1回目の言語が同じである場合、文章は正常に翻訳されません

### ISSUE THREAD

**Issue by jaotan** [jaoafa/Javajaotan2#389]
この事象のように、ランダムで抽出した翻訳1回目の言語が翻訳元の言語と同じ場合「言語間での翻訳はサポートされていません」が表示されます。
これは翻訳2回目以降に関しても同様の事象が見られる可能性があります。

## 不具合と思われるメッセージ (または報告)

2023-01-09 13:57:18.069 に送信された `jaotan#6066` による `#vc` でのメッセージ

メッセージ URL: https://discord.com/channels/597378876556967936/623153228267388958/1061871264492437524

## 不具合報告者

`kohonayoshi#0153` (`315726390844719114`)

**Comment by book000** [comment]
https://spread-sheets.com/function/google/detectlanguage-function/

めも。

**Comment by book000** [comment]
今日直せたら直す。

**Comment by book000** [comment]
まあ言語判別の処理を別個にし、ランダム言語ピックの前段階で入力値の言語を特定、ランダム言語ピックの段階で入力値の言語を弾くしかない。
それのついでにdetectlanguageapiへの依存を減らすかね。ゼロにするわけにもいかなそうだけど。

**Comment by book000** [comment]
ちなみに、この問題はコードを読む限り仕様上「翻訳1回目」のみに発生するもので2回目以降には発生しないようです。

**Comment by book000** [comment]
DETECTLANGUAGE関数、GoogleAppScriptだと現時点では使えないみたい。

https://issuetracker.google.com/issues/223022183

仕方ないからdetect language apiをそのまま使うしかないね
