### ISSUE TITLE
google検索コマンド

### ISSUE THREAD

**Issue by book000** [jaoafa/Javajaotan2#57]

**Comment by yuuahp** [comment]
どんな感じでやるんですか

**Comment by yuuahp** [comment]
https://www.google.com/search?q=powa みたいに言葉埋め込むとか
上位検索結果取ってくるとか？

**Comment by book000** [comment]
`google search java` とか `google search python` とか `google search api` とかぐぐってるけどうーんって感じ

**Comment by yuuahp** [comment]
Seleniumとかもうーん？

**Comment by book000** [comment]
天下のGoogleさんだから正直簡単にはいかんのよね〜

**Comment by yuuahp** [comment]
つら
