### ISSUE TITLE
運営の投票、誰がどこに投票したか表示するようにする

### ISSUE THREAD

**Issue by Omuretsu** [jaoafa/Javajaotan2#64]
## 対象の機能・コマンド

Javajaotan2
運営用審議チャンネル

## 強化・改善の内容

誰がどこに投票したか、投票終了時に表示するようにする。

**Comment by book000** [comment]
めも

- https://github.com/jaoafa/Javajaotan/blob/master/src/main/java/com/jaoafa/Javajaotan/Event/Event_ReactionAddEvent.java
- https://github.com/jaoafa/Javajaotan/blob/master/src/main/java/com/jaoafa/Javajaotan/Task/Task_MeetingVote.java
